version: '3.8'

services:
  backend:
    container_name: backend
    image: backend:ordery
    build:
      context: ./backend
      target: developement
    volumes:
      - ./backend:/home/node/app
    ports:
      - 3000:3000
    networks:
      - ordery
    env_file: .env
    restart: always

  frontend:
    container_name: frontend
    image: frontend:ordery
    build:
      context: ./frontend
      target: developement
    volumes:
      - ./frontend:/home/node/app
    networks:
      - ordery
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - backend
    restart: always

volumes:
  ordery:
    name: ordery

networks:
  ordery:
    name: ordery
    driver: bridge
